### ISSUE TITLE
Test do not pass without Logging In

### ISSUE THREAD

**Issue by ltanedo** [jayll/OpenSpot#65]
Some tests do not pass when user is not logged in.
[Screen Shot 2019-04-15 at 3.42.20 PM.png]
(https://images.zenhubusercontent.com/5c61d82bdf0733a30556afd6/bcb8b2f4-4ad3-482b-bebc-59f8d9bfccba)

**Comment by hisefath** [comment]
Those tests need a user to be logged in in order to work because in order to use the app, we need a user to be logged in. Thats why when running the consecutive tests, we have application boot up, and then login test. 

when unit testing, we run all the test consecutively to test that functionality, or else we would have a bunch of repeated code and requests to firebase to authenticate for any and every task we want to test.
